config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show]

  root "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = 25.times.map do |i|
      new_product(id: i, name: "Product #{i}")
    end

    @query = params[:query]
    @products = @products.select { |p| p.name.include?(@query) } if @query.present?
  end

  def show
    @product = new_product(
      id: params[:id],
      name: "Product #{params[:id]}",
      description: "Description #{params[:id]}"
    )
  end

  private

  def new_product(id:, name:, description: '')
    status = id.to_i.even? ? 'active' : 'inactive'
    OpenStruct.new(id: id, name: name, description: description, status: status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViewComponentWorkshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>
<div>
  <%= form_tag products_path, method: :get do %>
    <%= label_tag :query, 'Search:' %>
    <%= text_field_tag :query, @query %>
    <%= submit_tag 'Search' %>
  <% end %>
</div>

<br /><br />
<table id="products-list">
  <thead>
    <tr>Name</tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.name, product_path(product.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/show.html.erb
<div class="product">
  <p class="product_id">
    ID: <%= @product.id %>
  </p>

  <p class="product_name">
    Name: <%= @product.name %>
  </p>

  <p class="product_description">
    Description: <%= @product.description %>
  </p>

  <p class="product_status">
    Status: <span style="color: grey;"><%= @product.status %></span>
  </p>
</div>

<%# <%= render(ProductComponent.new(product: @product)) %1> %>